services:

  db:
    image: mysql:8.0
    container_name: health-db

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

    volumes:
      - health_mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./database/sample_data.sql:/docker-entrypoint-initdb.d/02-sample-data.sql:ro

    networks:
      - health-network

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s


  backend:
    build:
      context: ./backend

    container_name: health-backend

    restart: unless-stopped

    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      CORS_ORIGINS: ${CORS_ORIGINS}

    ports:
      - "8000:8000"

    depends_on:
      db:
        condition: service_healthy

    networks:
      - health-network


  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL}

    container_name: health-frontend

    restart: unless-stopped

    ports:
      - "80:80"

    depends_on:
      - backend

    networks:
      - health-network


networks:
  health-network:
    driver: bridge


volumes:
  health_mysql_data:
